portfolio:
    capital         : 100000
    margin          : 1.0
    cost_bps        : 0.0
    kelly_frac      : 0.1

system:
    system_name     : test
    signal_long     : mompos
    signal_short    : momneg
    profit_factor   : 
    stoploss_factor : 
    algo            : xgb
    prob_min        : 
    prob_max        : 

data:
    data_source     : polygon
    data_fractal    : 1D
    data_history    : 2000
    data_start_date : 
    data_end_date   : 
    data_start_time : "09:30"
    data_end_time   : "16:00"
    forecast_period : 5
    predict_history : 50
    subject         : stock
    target_group    : test
    cohort_group    : 

features :
    1D:    ['mompos', 'momneg', 'pivothigh', 'pivotlow', 'runs', 'runtotal', 'streak',
            'tdseqbuy', 'tdseqsell', 'zscore']
