league          : NCAAB
seasons         :
data_directory  : /Users/markconway/Projects/alphapy-root/alphapy-sports/NCAAB/data
prod_directory  : /Users/markconway/Projects/alphapy-root/alphapy-sports/Products/NCAAB
random_scoring  : False
points_max      : 110
points_min      : 65
rolling_window  : 3
