"""
Post composer for assembling Substack posts from Alfi data.
Templates for daily signals, backtest reports, and quick notes.
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

@dataclass
class PostSection:
    """A section of a composed post."""
    heading: str
    content: str  # HTML content
    section_type: str = "text"  # text, table, metric, embed


@dataclass
class ComposedPost:
    """A fully composed post ready for publishing."""
    title: str
    subtitle: str
    sections: List[PostSection] = field(default_factory=list)
    tags: List[str] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_html(self) -> str:
        """Render all sections to HTML."""
        parts = []
        for section in self.sections:
            if section.heading:
                parts.append(f"<h2>{section.heading}</h2>")
            parts.append(section.content)
        return "\n".join(parts)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "title": self.title,
            "subtitle": self.subtitle,
            "sections": [
                {"heading": s.heading, "content": s.content, "type": s.section_type}
                for s in self.sections
            ],
            "tags": self.tags,
            "html": self.to_html(),
            "created_at": self.created_at,
        }


class PostComposer:
    """Composes Substack posts from Alfi's signals, backtests, and market data."""

    def compose_daily_signal_post(
        self,
        signals: List[Dict],
        market_summary: Optional[Dict] = None,
    ) -> ComposedPost:
        """Compose a daily signals post with market summary."""
        today = datetime.now().strftime("%B %d, %Y")
        post = ComposedPost(
            title=f"Alfi's Market Signals — {today}",
            subtitle="AI-generated trading signals",
            tags=["signals", "trading", "ai"],
        )

        # Market summary section
        if market_summary:
            summary_html = self._render_market_summary(market_summary)
            post.sections.append(PostSection(
                heading="Market Overview",
                content=summary_html,
                section_type="text",
            ))

        # Signals section
        if signals:
            signals_html = self._render_signals_table(signals)
            post.sections.append(PostSection(
                heading=f"Today's Signals ({len(signals)})",
                content=signals_html,
                section_type="table",
            ))
        else:
            post.sections.append(PostSection(
                heading="Today's Signals",
                content="<p>No signals generated today. Markets are quiet.</p>",
            ))

        # Disclaimer
        post.sections.append(PostSection(
            heading="",
            content='<p><em>Generated by Alfi AI Trading Agent. Not financial advice. '
                    'Past performance does not guarantee future results.</em></p>',
        ))

        return post

    def compose_backtest_report(
        self,
        result: Dict,
    ) -> ComposedPost:
        """Compose a backtest report post."""
        config = result.get("config", {})
        metrics = result.get("metrics", {})
        strategy = config.get("strategy", "unknown")
        symbols = ", ".join(config.get("symbols", []))

        post = ComposedPost(
            title=f"Backtest Report: {strategy.replace('_', ' ').title()}",
            subtitle=f"Strategy performance on {symbols} ({config.get('start_date', '')} to {config.get('end_date', '')})",
            tags=["backtest", "strategy", strategy],
        )

        # Configuration section
        config_html = f"""
        <table>
            <tr><td><strong>Strategy</strong></td><td>{strategy.replace('_', ' ').title()}</td></tr>
            <tr><td><strong>Symbols</strong></td><td>{symbols}</td></tr>
            <tr><td><strong>Period</strong></td><td>{config.get('start_date', '')} to {config.get('end_date', '')}</td></tr>
            <tr><td><strong>Initial Capital</strong></td><td>${config.get('initial_capital', 100000):,.0f}</td></tr>
        </table>
        """
        post.sections.append(PostSection(
            heading="Configuration",
            content=config_html,
            section_type="table",
        ))

        # Metrics section
        metrics_html = self._render_metrics(metrics)
        post.sections.append(PostSection(
            heading="Performance Metrics",
            content=metrics_html,
            section_type="metric",
        ))

        # Trades summary
        trades = result.get("trades", [])
        if trades:
            trade_count = len(trades)
            post.sections.append(PostSection(
                heading=f"Trade Log ({trade_count} trades)",
                content=self._render_trades_table(trades[:20]),
                section_type="table",
            ))
            if trade_count > 20:
                post.sections.append(PostSection(
                    heading="",
                    content=f"<p><em>Showing first 20 of {trade_count} trades.</em></p>",
                ))

        # Disclaimer
        post.sections.append(PostSection(
            heading="",
            content='<p><em>Generated by Alfi AI Trading Agent. Not financial advice.</em></p>',
        ))

        return post

    def compose_signal_note(
        self,
        signal: Dict,
    ) -> ComposedPost:
        """Compose a quick single-signal note."""
        symbol = signal.get("symbol", "???")
        direction = signal.get("direction", "long")
        confidence = signal.get("confidence", 0)

        post = ComposedPost(
            title=f"Signal: {direction.upper()} {symbol} ({confidence:.0%} confidence)",
            subtitle=signal.get("reasoning", ""),
            tags=["signal", symbol.lower(), direction],
        )

        signal_html = f"""
        <table>
            <tr><td><strong>Symbol</strong></td><td>{symbol}</td></tr>
            <tr><td><strong>Direction</strong></td><td>{direction.upper()}</td></tr>
            <tr><td><strong>Confidence</strong></td><td>{confidence:.0%}</td></tr>
            <tr><td><strong>Entry Price</strong></td><td>${signal.get('entry_price', 0):,.2f}</td></tr>
            <tr><td><strong>Stop Loss</strong></td><td>${signal.get('stop_loss', 0):,.2f}</td></tr>
            <tr><td><strong>Take Profit</strong></td><td>${signal.get('take_profit', 0):,.2f}</td></tr>
            <tr><td><strong>Risk/Reward</strong></td><td>{signal.get('risk_reward_ratio', 0):.1f}x</td></tr>
            <tr><td><strong>Skill</strong></td><td>{signal.get('skill_name', 'N/A')}</td></tr>
        </table>
        <p><strong>Reasoning:</strong> {signal.get('reasoning', 'N/A')}</p>
        """
        post.sections.append(PostSection(
            heading="Signal Details",
            content=signal_html,
            section_type="table",
        ))

        post.sections.append(PostSection(
            heading="",
            content='<p><em>Generated by Alfi AI Trading Agent. Not financial advice.</em></p>',
        ))

        return post

    def compose_custom(self, title: str, markdown: str, tags: Optional[List[str]] = None) -> ComposedPost:
        """Compose a custom post from markdown."""
        from substack_publisher import SubstackPublisher

        post = ComposedPost(
            title=title,
            subtitle="",
            tags=tags or [],
        )
        html = SubstackPublisher.markdown_to_html(markdown)
        post.sections.append(PostSection(heading="", content=html))
        return post

    # ---- Rendering helpers ----

    def _render_market_summary(self, summary: Dict) -> str:
        total = summary.get("total_symbols", 0)
        timestamp = summary.get("timestamp", "")
        return f"""
        <p>Monitoring <strong>{total}</strong> symbols.
        Last updated: {timestamp}</p>
        """

    def _render_signals_table(self, signals: List[Dict]) -> str:
        rows = []
        for s in signals:
            direction = s.get("direction", "long")
            color = "green" if direction == "long" else "red"
            rows.append(f"""
            <tr>
                <td><strong>{s.get('symbol', '')}</strong></td>
                <td style="color: {color}">{direction.upper()}</td>
                <td>{s.get('confidence', 0):.0%}</td>
                <td>${s.get('entry_price', 0):,.2f}</td>
                <td>{s.get('risk_reward_ratio', 0):.1f}x</td>
                <td>{s.get('skill_name', '')}</td>
            </tr>
            """)

        return f"""
        <table>
            <thead>
                <tr>
                    <th>Symbol</th><th>Direction</th><th>Confidence</th>
                    <th>Entry</th><th>R:R</th><th>Strategy</th>
                </tr>
            </thead>
            <tbody>{''.join(rows)}</tbody>
        </table>
        """

    def _render_metrics(self, metrics: Dict) -> str:
        def fmt(val, suffix="", pct=False):
            if val is None:
                return "N/A"
            if pct:
                return f"{val:.2f}%"
            if isinstance(val, float):
                return f"{val:,.2f}{suffix}"
            return f"{val}{suffix}"

        return f"""
        <table>
            <tr><td><strong>Total Return</strong></td><td>{fmt(metrics.get('total_return_pct'), pct=True)}</td></tr>
            <tr><td><strong>Total Trades</strong></td><td>{metrics.get('total_trades', 0)}</td></tr>
            <tr><td><strong>Win Rate</strong></td><td>{fmt(metrics.get('win_rate'), pct=True)}</td></tr>
            <tr><td><strong>Sharpe Ratio</strong></td><td>{fmt(metrics.get('sharpe_ratio'))}</td></tr>
            <tr><td><strong>Max Drawdown</strong></td><td>{fmt(metrics.get('max_drawdown_pct'), pct=True)}</td></tr>
            <tr><td><strong>Profit Factor</strong></td><td>{fmt(metrics.get('profit_factor'))}</td></tr>
            <tr><td><strong>Final Equity</strong></td><td>${fmt(metrics.get('final_equity'))}</td></tr>
        </table>
        """

    def _render_trades_table(self, trades: List[Dict]) -> str:
        if not trades:
            return "<p>No trades.</p>"

        # Get column headers from first trade
        headers = list(trades[0].keys())[:8]
        header_row = "".join(f"<th>{h.replace('_', ' ').title()}</th>" for h in headers)

        rows = []
        for t in trades:
            cells = []
            for h in headers:
                val = t.get(h, "")
                if isinstance(val, float):
                    cells.append(f"<td>{val:.2f}</td>")
                else:
                    cells.append(f"<td>{val}</td>")
            rows.append(f"<tr>{''.join(cells)}</tr>")

        return f"""
        <table>
            <thead><tr>{header_row}</tr></thead>
            <tbody>{''.join(rows)}</tbody>
        </table>
        """

