"""Trade signal dataclass and aggregation logic."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional
import uuid


class SignalDirection(str, Enum):
    LONG = "long"
    SHORT = "short"


class SignalStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXECUTED = "executed"
    EXPIRED = "expired"
    CANCELLED = "cancelled"


@dataclass
class TradeSignal:
    """A trading signal generated by skill evaluation."""

    symbol: str
    direction: SignalDirection
    confidence: float  # 0.0 - 1.0
    entry_price: float
    stop_loss: float
    take_profit: float
    reasoning: str
    skill_name: str

    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    status: SignalStatus = SignalStatus.PENDING
    created_at: datetime = field(default_factory=datetime.now)
    position_size_pct: float = 0.0  # Filled by risk manager
    risk_reward_ratio: float = 0.0
    metadata: Dict = field(default_factory=dict)

    def __post_init__(self):
        if self.stop_loss > 0 and self.entry_price > 0:
            risk = abs(self.entry_price - self.stop_loss)
            reward = abs(self.take_profit - self.entry_price)
            self.risk_reward_ratio = round(reward / risk, 2) if risk > 0 else 0.0

    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "symbol": self.symbol,
            "direction": self.direction.value,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "risk_reward_ratio": self.risk_reward_ratio,
            "reasoning": self.reasoning,
            "skill_name": self.skill_name,
            "status": self.status.value,
            "created_at": self.created_at.isoformat(),
            "position_size_pct": self.position_size_pct,
        }


class SignalAggregator:
    """Deduplicates, ranks, and filters trade signals."""

    def aggregate(self, signals: List[TradeSignal]) -> List[TradeSignal]:
        """Deduplicate and rank signals by confidence."""
        if not signals:
            return []

        # Group by symbol
        by_symbol: Dict[str, List[TradeSignal]] = {}
        for sig in signals:
            by_symbol.setdefault(sig.symbol, []).append(sig)

        result: List[TradeSignal] = []
        conflicts: List[str] = []

        for symbol, sigs in by_symbol.items():
            if len(sigs) == 1:
                result.append(sigs[0])
                continue

            # Check for directional conflicts
            directions = {s.direction for s in sigs}
            if len(directions) > 1:
                conflicts.append(symbol)
                # Take the higher-confidence signal
                best = max(sigs, key=lambda s: s.confidence)
                best.metadata["conflict_resolved"] = True
                best.metadata["competing_signals"] = len(sigs)
                result.append(best)
            else:
                # Same direction — take highest confidence
                best = max(sigs, key=lambda s: s.confidence)
                best.metadata["merged_from"] = len(sigs)
                result.append(best)

        # Sort by confidence descending
        result.sort(key=lambda s: s.confidence, reverse=True)
        return result
